[project]
name = "image-similarity"
version = "0.1.0"
description = "Basic Image Embedding and Retrieval"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "python-arango>=8.2.5",
]
